---
stages:
  - lint
  - build
  - test

include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Rust.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'

lint:yaml:
  stage: lint
  extends:
    - .yaml-lint
  needs: []

build:
  stage: build
  extends:
    - .rust-build
  needs: []
  artifacts:
    paths:
      - ./target
    expire_in: 2 hours

test:
  stage: test
  extends:
    - .rust-test
  needs: []
