---
include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Rust.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'

lint:yaml:
  extends:
    - .yaml-lint
  needs: []

build:rust:
  extends:
    - .rust-build
  needs: []

test:rust:
  extends:
    - .rust-test
  needs: []
