stages:
  - build
  - test

include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file: '/templates/Rust.gitlab-ci.yml'

build:
  stage: build
  extends:
    - .rust-build
  artifacts:
    paths:
      - ./target
    expire_in: 2 hours

test:
  stage: test
  extends:
    - .rust-test
