---
include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Rust.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'

lint:yaml:
  extends:
    - .yaml-lint
  needs: []

build:rust:
  extends:
    - .rust-build
  needs: []

test:rust:
  extends:
    - .rust-test
  needs: []

test:python:
  image: python:3.10.5-slim-buster
  before_script:
    - python -m venv .venv
    - .venv/bin/python --version
    - .venv/bin/python -m pip install --upgrade pip
    - .venv/bin/pip --version
    - .venv/bin/pip install -r requirements.txt
  script: |
    .venv/bin/python -m unittest discover python/tests
  interruptible: true
  needs: []
  tags:
    - docker
