stages:
  - build
  - test

variables:
  RUSTFLAGS: "-Zinstrument-coverage"

build:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - rustc --version
    - cargo --version
    - rustup --version
    - rustup component add llvm-tools-preview
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - target
    expire_in: 2 hours
  tags:
    - docker

test:
  stage: test
  image: rustlang/rust:nightly
  before_script:
    - rustc --version
    - cargo --version
    - rustup --version
    - rustup component add llvm-tools-preview
  script: |
    apt-get update -qq && apt-get install -y -qq lcov --no-install-recommends
    cargo install --color=always --force grcov
    cargo test --workspace --verbose
    grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o coverage.info
    lcov -l coverage.info
  coverage: '/Total:\|\s*(\d+\.\d+)%/'
  variables:
    LLVM_PROFILE_FILE: "advent-of-code-%p-%m.profraw"
  needs:
    - build
  tags:
    - docker
